/**
 * Kinow API
 * Public api for Kinow back office
 *
 * OpenAPI spec version: 1.0.72
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Image'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Image'));
  } else {
    // Browser globals (root is window)
    if (!root.KinowJavascriptSdk) {
      root.KinowJavascriptSdk = {};
    }
    root.KinowJavascriptSdk.ManufacturersApi = factory(root.KinowJavascriptSdk.ApiClient, root.KinowJavascriptSdk.Image);
  }
}(this, function(ApiClient, Image) {
  'use strict';

  /**
   * Manufacturers service.
   * @module api/ManufacturersApi
   * @version 1.0.72
   */

  /**
   * Constructs a new ManufacturersApi. 
   * @alias module:api/ManufacturersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Please, use __/directors/{actor_id}/cover__
     * @param {Integer} manufacturerId ID of the manufacturer to fetch
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Image} and HTTP response
     */
    this.getManufacturerCoverImageWithHttpInfo = function(manufacturerId) {
      var postBody = null;

      // verify the required parameter 'manufacturerId' is set
      if (manufacturerId === undefined || manufacturerId === null) {
        throw new Error("Missing the required parameter 'manufacturerId' when calling getManufacturerCoverImage");
      }


      var pathParams = {
        'manufacturer_id': manufacturerId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Image;

      return this.apiClient.callApi(
        '/manufacturers/{manufacturer_id}/cover', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Please, use __/directors/{actor_id}/cover__
     * @param {Integer} manufacturerId ID of the manufacturer to fetch
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Image}
     */
    this.getManufacturerCoverImage = function(manufacturerId) {
      return this.getManufacturerCoverImageWithHttpInfo(manufacturerId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
